annotations:
  max_scale_version: 24.04.2.3
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: 'false'
  truecharts.org/category: operators
  truecharts.org/max_helm_version: '3.15'
  truecharts.org/min_helm_version: '3.11'
  truecharts.org/train: system
apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    version: 24.1.10
    repository: https://petersandor.github.io/truecharts-common
    condition: ''
    alias: ''
    tags: []
    import-values: []
  - name: nvidia-device-plugin
    version: 0.16.2
    repository: https://nvidia.github.io/k8s-device-plugin
    condition: ''
    alias: nvdp
    tags: []
    import-values: []
deprecated: false
description: NVIDIA device plugin for Kubernetes
home: https://truecharts.org/charts/system/nvidia-device-plugin
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nvidia-device-plugin.webp
keywords:
  - nvidia
  - plugins
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: kubeapps
sources:
  - https://github.com/truecharts/charts/tree/master/charts/system/nvidia-device-plugin
  - https://cert-manager.io/
  - https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#deployment-via-helm
type: application
version: 2.1.3
